name: Lint

on: [push, pull_request]


jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      uses: actions/checkout@v2
      

      - name: Setup python
      uses: actions/setup-python@v2
    

      - name: Install & Update
      run: |
        pip install --upgrade pip wheel
        pip install black
      

      - name: Run black
      run: black --check *.py app/*.py
